name: mca_sdk
description: MyCover SDK
version: 0.0.1
homepage: https://github.com/enypeter/mca_sdk

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_datetime_picker:
  connectivity_plus:
#    git:
#      url: https://github.com/Realank/flutter_datetime_picker.git
#      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/images/

